# Generated by Django 3.2.11 on 2022-02-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_crm', '0005_auto_20220202_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('incoming', 'Future event'), ('over', 'Past event')], default='incoming', max_length=20),
        ),
    ]
